#! /bin/sh

#Startup
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --set-auto ~/Downloads/ODST.jpeg
picom -CGb
xrandr --refresh 144
$HOME/.config/polybar/launch.sh
dunst &
polybar example &

###########################################
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
XF86AudioPlay exec playerctl play-pause
XF86AudioPause exec playerctl play-pause
XF86AudioNext exec playerctl next
XF86AudioPrev exec playerctl previous
